---
- name: Install Docker on Managed Nodes
  hosts: all
  become: true

  tasks:

    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Enable Docker service
      service:
        name: docker
        enabled: yes

    - name: Verify Docker installation
      command: docker --version
      register: docker_output

    - name: Display Docker version
      debug:
        var: docker_output.stdout
